gds:
  cell_name: TEST
  default_layer:
  - 1
  - 0
  input_file: null
  output_file: test_output.gds
global:
  dbu: 0.001
  fillet:
    default_action: auto
    interactive: false
    precision: 0.01
  layer_mapping:
    file: test_layer_mapping.txt
    save: true
shapes:
- cell: TEST
  fillet_radius: 0
  layer:
  - 1
  - 0
  type: polygon
  vertices: 0,0;10,0;10,10;0,10
- cell: TEST
  fillet_radius: 0
  layer:
  - 2
  - 0
  ring_num: 2
  ring_space: 2
  ring_width: 2
  type: rings
  vertices: 0,0;10,0;10,10;0,10
