global:
  dbu: 0.001
  fillet:
    interactive: false
    default_action: "auto"
    precision: 0.01
  layer_mapping:
    save: true
    file: "layer_mapping.txt"

gds:
  input_file: null
  output_file: "square_example.gds"
  cell_name: "TOP"
  default_layer: [1, 0]

shapes:
  - type: "polygon"
    name: "方形"
    vertices: "0,0:10,0:10,10:0,10"
    layer: [1, 0]
    fillet:
      type: "arc"
      radius: 1
    zoom: 1
    
  - type: "rings"
    name: "方形环阵列"
    vertices: "0,0:20,0:20,20:0,20"
    ring_width: 1
    ring_space: 1
    ring_num: 3
    layer: [2, 0]
    fillet:
      type: "arc"
      radius: 1.5
    zoom: 0 